# file name: problemSetDay2.py
name = input('what is your name?')
print('your name is ' + name)
birthday = input('when is your birthday?')
print('your birthday is on ' + birthday)
grade = input('what grade are you in?')
print('you are in ' + grade)
school = input('what school do you go to?')
print('you go to ' + school)
Favorite_subject = input('what is your favorite subject in school?')
print('our favorite subject in schoo is ' + Favorite_subject)
Work = input('what do you want to be when you grow up?')
print('you want to become a ' + Work)
print('thank you for filling this form out!')
x = input('chose a variable')
print('you chose' + x)
